# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# ══════════════════════════════════════════════════════════════════════════════
# CodeRabbit Configuration — kodflow/devcontainer-template
# Goal: high-quality reviews with controlled token usage
# Strategy:
# - Balanced reviewer profile to avoid noise while keeping strong signal
# - Diff-first, boundary-focused feedback
# - Strong supply-chain and secrets hygiene
# ══════════════════════════════════════════════════════════════════════════════

language: "fr-FR"

reviews:
  # "assertive" provides thorough, strict reviews with detailed feedback
  # This generates more comments but ensures high-quality code review
  profile: "assertive"

  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  collapse_walkthrough: true

  # Token/noise reduction
  commit_status: false
  review_status: false
  poem: false
  sequence_diagrams: false
  in_progress_fortune: false
  changed_files_summary: false
  suggested_reviewers: false

  # Rely on CLAUDE.md and path-specific instructions
  enable_prompt_for_ai_agents: false

  # Files out of scope for reviews
  path_filters:
    # Docs / meta
    - "!**/*.md"
    - "!**/.gitignore"
    - "!**/.gitattributes"
    - "!**/LICENSE*"
    - "!**/CHANGELOG*"
    - "!**/CODEOWNERS"

    # Lock / vendor / build outputs
    - "!**/*.lock"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/target/**"
    - "!**/.terraform/**"
    - "!**/vendor/**"

    # Devcontainer prompts / assets
    - "!**/.devcontainer/images/.claude/**"

  # Review instructions by file type (high signal only)
  path_instructions:
    # ─────────────────────────────────────────────────────────────────────────
    # Shell
    # ─────────────────────────────────────────────────────────────────────────
    - path: "**/*.{sh,bash,zsh}"
      instructions: |
        Shell requirements (production-grade):
        - Always use: set -euo pipefail (bash) and a safe IFS if needed.
        - Strict quoting; reject unintended word splitting or globbing.
        - No plaintext secrets (tokens, passwords, private keys) — BLOCKER.
        - Idempotency: re-running the script must not break state.
        - Robustness: handle errors (exit codes), timeouts, retries (with backoff for network).
        - Compatibility: explicitly target bash vs POSIX; if POSIX, avoid arrays/process substitution.
        - Output: clear logs; never leak sensitive variables.
        - Require ShellCheck compliance (reference SCxxxx with fixes).

    # ─────────────────────────────────────────────────────────────────────────
    # YAML
    # ─────────────────────────────────────────────────────────────────────────
    - path: "**/*.{yml,yaml}"
      instructions: |
        YAML requirements:
        - Readability: stable indentation; avoid unnecessary duplication.
        - Security: no sensitive values in plaintext (even in examples).
        - GitHub Actions: minimal permissions, pin actions (SHA or strict tag), avoid unnecessary checkout.
        - Configs: prefer schemas/validation where possible; avoid ambiguous fields.

    # ─────────────────────────────────────────────────────────────────────────
    # JSON (DevContainer / tooling)
    # ─────────────────────────────────────────────────────────────────────────
    - path: "**/*.json"
      instructions: |
        JSON requirements:
        - Strict valid JSON; structure must match expected schemas.
        - DevContainer: prefer official features; avoid fragile overrides.
        - No plaintext secrets (even partially masked) — BLOCKER.
        - Version consistency (images, features, actions) with justification if pinned.

    # ─────────────────────────────────────────────────────────────────────────
    # DevContainer core
    # ─────────────────────────────────────────────────────────────────────────
    - path: "**/.devcontainer/devcontainer.json"
      instructions: |
        DevContainer review:
        - Reproducibility: deterministic builds (pinned versions), no "latest".
        - Security: non-root user when possible; minimal capabilities; cautious mounts.
        - DX: postCreate/postStart commands must be idempotent; no irreversible side effects.
        - Networking: proxies/registries handled explicitly; no implicit TLS bypass.

    # ─────────────────────────────────────────────────────────────────────────
    # Dockerfiles (if present)
    # ─────────────────────────────────────────────────────────────────────────
    - path: "**/Dockerfile"
      instructions: |
        Dockerfile review:
        - Pin versions (explicit base image tags, ideally digests).
        - Non-root USER (or explicit justification).
        - Reduce surface area: minimal layers, proper cache usage, clean package managers.
        - Secrets: never via persistent ARG/ENV; no tokens in RUN.
        - Hadolint: raise relevant warnings with fixes.

    # ─────────────────────────────────────────────────────────────────────────
    # GitHub Actions
    # ─────────────────────────────────────────────────────────────────────────
    - path: "**/.github/workflows/**"
      instructions: |
        GitHub Actions review (security / supply chain):
        - Permissions: explicitly define at workflow/job level; least privilege.
        - Third-party actions: pin versions (prefer SHAs); avoid unmaintained actions.
        - Secrets: never echo; be careful with logs; limit token scope.
        - Concurrency: avoid conflicting jobs; use concurrency when appropriate.
        - Cache: stable keys and correct paths; never cache secrets.

  auto_review:
    enabled: true
    auto_incremental_review: false
    drafts: false
    base_branches:
      - "main"
    ignore_usernames:
      - "dependabot[bot]"
      - "renovate[bot]"
      - "github-actions[bot]"

  # Tools with high ROI for this repository type
  tools:
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    # Enable hadolint if Dockerfiles are part of the template
    hadolint:
      enabled: true
    # Semgrep can add noise/cost; keep disabled by default
    semgrep:
      enabled: false

  # Disable auto-generation to save tokens and avoid hallucinations
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

chat:
  auto_reply: true
  art: false

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
      - "**/CONTRIBUTING.md"
      - "**/ARCHITECTURE.md"
