# =============================================================================
# CodeRabbit Configuration - supervizio/daemon
# =============================================================================
# PID1-capable process supervisor for containers and Unix systems
# Hexagonal architecture (DDD) | Go 1.25+ | Multi-platform (Linux/BSD/macOS)
# =============================================================================

language: fr-FR

tone_instructions: >
  Technical, rigorous. PID1 supervisor - bugs crash containers.
  Focus: signals, lifecycle, goroutines, FD leaks, shutdown. No fluff.

early_access: false
enable_free_tier: true
inheritance: false

# =============================================================================
# Reviews
# =============================================================================
reviews:
  profile: assertive
  request_changes_workflow: false

  # Summary
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_instructions: >
    Changelog: 5-10 bullet points max.
    Sections: "Breaking Changes" (if any), "Platform Impact" (Linux/BSD/macOS),
    "Concurrency Concerns", "Performance Impact".
    For process supervisor: mention signal handling, lifecycle, resource cleanup changes.

  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: >
    Format: <scope>: <verb> <object>
    Scopes: supervisor, lifecycle, process, health, metrics, tui, grpc, config, e2e, ci
    Examples: supervisor: fix graceful shutdown race, lifecycle: add exponential backoff

  # Status & Details
  review_status: true
  review_details: true
  commit_status: true
  fail_commit_status: true

  # Display
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true

  # Analysis
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true

  # Labels & Reviewers
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false

  # Noise reduction
  in_progress_fortune: false
  poem: false

  # AI agents integration (Claude Code compatible)
  enable_prompt_for_ai_agents: true

  # ---------------------------------------------------------------------------
  # Path Filters
  # ---------------------------------------------------------------------------
  path_filters:
    # Include
    - "**/*.go"
    - "**/*.mod"
    - "**/*.sum"
    - "**/*.proto"
    - "**/*.sh"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.md"
    - "**/Dockerfile*"
    - "**/Vagrantfile"
    - "**/Makefile"
    - "**/nfpm.yaml"
    # Exclude generated
    - "!**/*.pb.go"
    - "!**/*_grpc.pb.go"
    - "!**/wire_gen.go"
    - "!**/*_mock.go"
    - "!**/*.gen.go"
    # Exclude vendored
    - "!**/vendor/**"
    - "!**/third_party/**"
    - "!**/dist/**"
    - "!**/bin/**"
    - "!**/coverage/**"
    # Exclude devcontainer internals (managed separately)
    - "!.devcontainer/images/**"
    - "!.devcontainer/features/**"

  # ---------------------------------------------------------------------------
  # Path Instructions (Context-Aware)
  # ---------------------------------------------------------------------------
  path_instructions:
    # -------------------------------------------------------------------------
    # Go Source Code
    # -------------------------------------------------------------------------
    - path: "src/**/*.go"
      instructions: |
        **Process Supervisor Requirements:**
        - Signal handling: SIGTERM, SIGINT, SIGHUP, SIGCHLD must be handled correctly
        - Graceful shutdown: All child processes must be stopped before exit
        - Resource cleanup: File descriptors, goroutines, channels must not leak
        - PID1 mode: Must reap zombies, handle orphan adoption

        **Go Best Practices:**
        - context.Context: First param, never stored in struct, proper timeout/cancel
        - Error handling: Wrap with context (fmt.Errorf("...: %w", err)), no panic for flow
        - Concurrency: Detect data races, goroutine leaks, blocking channels, proper sync usage
        - Performance: Avoid allocations in hot paths, use strings.Builder, pre-allocate slices

        **Hexagonal Architecture:**
        - Domain layer (domain/): No external dependencies, pure business logic
        - Application layer (application/): Orchestration only, no infrastructure
        - Infrastructure layer (infrastructure/): Implements domain ports

        **Testing:**
        - Race detection required (-race flag)
        - Table-driven tests with t.Parallel() where safe
        - External tests (*_external_test.go) for black-box, internal (*_internal_test.go) for white-box

    # -------------------------------------------------------------------------
    # Domain Layer (Critical - Core Business Logic)
    # -------------------------------------------------------------------------
    - path: "src/internal/domain/**/*.go"
      instructions: |
        **DOMAIN LAYER - CRITICAL**
        - ZERO external dependencies (no infrastructure imports)
        - Pure business logic and domain entities
        - Port interfaces only (no implementations)
        - Value objects must be immutable
        - Reject any import from infrastructure/ or application/

    # -------------------------------------------------------------------------
    # Application Layer (Use Cases)
    # -------------------------------------------------------------------------
    - path: "src/internal/application/**/*.go"
      instructions: |
        **APPLICATION LAYER**
        - Orchestrates domain entities and ports
        - May depend on domain/, never on infrastructure/
        - Use cases should be testable without infrastructure
        - Supervisor: Verify service lifecycle state machine
        - Lifecycle: Check restart policy, backoff, event emission

    # -------------------------------------------------------------------------
    # Infrastructure Layer (Adapters)
    # -------------------------------------------------------------------------
    - path: "src/internal/infrastructure/**/*.go"
      instructions: |
        **INFRASTRUCTURE LAYER**
        - Implements domain port interfaces
        - Platform-specific code must use build tags
        - Process handling: exec.Cmd cleanup, signal forwarding, PTY handling
        - Metrics: procfs/sysfs reading, no exec.Command for system info
        - Health checks: Proper timeouts, context cancellation

    # -------------------------------------------------------------------------
    # Platform-Specific Code
    # -------------------------------------------------------------------------
    - path: "src/**/*_linux.go"
      instructions: |
        **Linux-specific code:**
        - procfs/sysfs paths must be correct (/proc, /sys)
        - cgroup v1/v2 detection and handling
        - Signal handling (SIGCHLD, PR_SET_CHILD_SUBREAPER)
        - seccomp, namespaces, capabilities if used

    - path: "src/**/*_darwin.go"
      instructions: |
        **macOS-specific code:**
        - Different signal semantics than Linux
        - No procfs - use sysctl or mach APIs
        - Sandbox restrictions awareness

    - path: "src/**/*_bsd.go"
      instructions: |
        **BSD-specific code (FreeBSD/OpenBSD/NetBSD/DragonFly):**
        - procfs may not be mounted by default
        - kqueue for event notification
        - Different init system integration (rc.d)

    # -------------------------------------------------------------------------
    # Tests
    # -------------------------------------------------------------------------
    - path: "**/*_test.go"
      instructions: |
        **Test Requirements:**
        - Arrange/Act/Assert pattern
        - No time.Sleep for synchronization - use channels, WaitGroups, or fake clocks
        - Concurrent tests: Use t.Parallel() only when safe
        - Process tests: Clean up spawned processes in t.Cleanup()
        - Error assertions: Check specific error types/messages
        - Coverage: New features require tests, bugfixes require regression tests

    - path: "**/*_external_test.go"
      instructions: |
        **Black-box tests (package_test):**
        - Test only exported API
        - Focus on integration and behavior
        - May use test fixtures

    - path: "**/*_internal_test.go"
      instructions: |
        **White-box tests (same package):**
        - Test internal implementation details
        - State machine transitions
        - Edge cases in private functions

    # -------------------------------------------------------------------------
    # E2E Tests
    # -------------------------------------------------------------------------
    - path: "e2e/**/*.go"
      instructions: |
        **E2E Tests (testcontainers-go):**
        - Container lifecycle cleanup in t.Cleanup()
        - Reasonable timeouts (15min max for VM tests)
        - Idempotent tests - can run multiple times
        - Platform matrix coverage (Debian, Alpine, Fedora, BSD variants)

    - path: "e2e/**/*.sh"
      instructions: |
        **E2E Shell Scripts:**
        - set -euo pipefail at the top
        - Portable POSIX where possible (sh vs bash)
        - Cleanup on exit (trap)
        - Clear error messages with exit codes

    - path: "e2e/Dockerfile*"
      instructions: |
        **E2E Dockerfiles:**
        - Multi-stage if needed for build
        - Minimal base images (Alpine preferred)
        - Non-root user where possible
        - HEALTHCHECK if the container runs services

    - path: "e2e/Vagrantfile"
      instructions: |
        **Vagrant Configuration:**
        - Pin box versions for reproducibility
        - Minimal provisioning (boxes should be ready)
        - rsync for folder sync (not NFS for CI)
        - Resource limits (memory, CPU)

    # -------------------------------------------------------------------------
    # Protocol Buffers
    # -------------------------------------------------------------------------
    - path: "**/*.proto"
      instructions: |
        **Protobuf Requirements:**
        - Never reuse field tags - reserve removed fields
        - Backwards compatible changes only (additive)
        - Clear message naming (ProcessMetrics, not Metrics)
        - Document fields with comments
        - Use well-known types (google.protobuf.Timestamp, Duration)

    # -------------------------------------------------------------------------
    # CI/CD Workflows
    # -------------------------------------------------------------------------
    - path: ".github/workflows/**"
      instructions: |
        **GitHub Actions Requirements:**
        - Pin actions by SHA, not tags (e.g., actions/checkout@SHA)
        - Go module caching (cache: true, cache-dependency-path)
        - Fail fast where appropriate
        - Secrets: Never echo, use GitHub Secrets
        - Matrix: Cover amd64/arm64, major distros
        - Timeouts: Set explicit timeouts

    # -------------------------------------------------------------------------
    # Shell Scripts
    # -------------------------------------------------------------------------
    - path: "**/*.sh"
      instructions: |
        **Shell Script Requirements:**
        - Shebang: #!/bin/sh for POSIX, #!/usr/bin/env bash for bash-specific
        - set -euo pipefail (bash) or set -eu (sh)
        - Quote all variables: "$VAR" not $VAR
        - No secrets in echo/printf
        - Cleanup traps for temporary files
        - Portable commands (avoid GNU-specific flags on BSD)

    - path: "setup/**/*.sh"
      instructions: |
        **Installation Scripts:**
        - Must work on: Debian, RHEL, Alpine, FreeBSD, OpenBSD, NetBSD, macOS
        - Detect init system (systemd, sysvinit, openrc, runit, launchd, rc.d)
        - Non-destructive: Backup existing configs
        - Idempotent: Safe to run multiple times
        - Uninstall support

    # -------------------------------------------------------------------------
    # Configuration
    # -------------------------------------------------------------------------
    - path: "**/*.yaml"
      instructions: |
        **YAML Configuration:**
        - Schema validation where possible
        - Sensible defaults documented
        - Environment variable substitution support
        - No hardcoded paths (configurable base dirs)

    - path: "nfpm.yaml"
      instructions: |
        **nfpm Package Configuration:**
        - Version from environment variable
        - Correct file permissions (755 for binaries, 644 for configs)
        - Proper dependencies declaration
        - Pre/post install scripts tested

    - path: "src/.golangci.yml"
      instructions: |
        **golangci-lint Configuration:**
        - Justify any disabled linters
        - Strict settings for new code
        - Generated file exclusions
        - Platform-specific file handling

    # -------------------------------------------------------------------------
    # Documentation
    # -------------------------------------------------------------------------
    - path: "**/*.md"
      instructions: |
        **Documentation:**
        - Keep in sync with code changes
        - Runnable examples where applicable
        - CLAUDE.md files: Accurate structure, dependencies, commands
        - No stale API references

    - path: "**/CLAUDE.md"
      instructions: |
        **CLAUDE.md (AI Context Files):**
        - Accurate package structure
        - Current dependencies and relationships
        - Correct command examples
        - Update when package structure changes

  # ---------------------------------------------------------------------------
  # Auto Review Settings
  # ---------------------------------------------------------------------------
  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "wip"
      - "draft"
      - "do not review"
      - "[skip ci]"
    labels:
      - "!wip"
      - "!skip-review"
    drafts: false
    base_branches:
      - "main"
      - "master"
      - "release/.*"
    ignore_usernames: []

  # ---------------------------------------------------------------------------
  # Finishing Touches
  # ---------------------------------------------------------------------------
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  # ---------------------------------------------------------------------------
  # Pre-Merge Checks
  # ---------------------------------------------------------------------------
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 70
    title:
      mode: error
      requirements: >
        Format: <scope>: <verb> <object>. Max 72 chars.
        Valid scopes: supervisor, lifecycle, process, health, metrics, tui, grpc, config, e2e, ci, docs
        No "WIP", "Update", "Fix" alone.
    description:
      mode: warning
    issue_assessment:
      mode: warning
    custom_checks:
      - name: "Signal & Lifecycle Safety"
        instructions: >
          ERROR if: Signal handlers missing, child processes not cleaned up,
          zombie processes possible, goroutine leaks on shutdown.
        mode: error

      - name: "Context & Error Handling"
        instructions: >
          ERROR if: Errors ignored, panic for control flow, context missing
          on I/O, no timeouts on blocking calls.
        mode: error

      - name: "Concurrency Safety"
        instructions: >
          ERROR if: Data races, channels never closed, mutex held across
          blocking calls.
        mode: error

      - name: "Security"
        instructions: >
          ERROR if: Secrets hardcoded/logged, command injection, path traversal,
          TLS verification disabled.
        mode: error

      - name: "Testing & Platform"
        instructions: >
          WARNING if: New code without tests, no -race tests, Linux-specific
          code without build tags, hardcoded /proc paths.
        mode: warning

  # ---------------------------------------------------------------------------
  # Tools
  # ---------------------------------------------------------------------------
  tools:
    # Go
    golangci-lint:
      enabled: true
      config_file: "src/.golangci.yml"

    # Protobuf
    buf:
      enabled: true

    # Security
    gitleaks:
      enabled: true
    osvScanner:
      enabled: true

    # CI/Infra
    actionlint:
      enabled: true
    yamllint:
      enabled: true
    shellcheck:
      enabled: true
    checkov:
      enabled: true

    # Docs
    markdownlint:
      enabled: true
    languagetool:
      enabled: true
      level: default
      enabled_only: false

    # GitHub integration
    github-checks:
      enabled: true
      timeout_ms: 300000 # 5 min for E2E tests

    # Disabled (not applicable to Go project)
    biome:
      enabled: false
    eslint:
      enabled: false
    ruff:
      enabled: false
    flake8:
      enabled: false
    pylint:
      enabled: false
    phpstan:
      enabled: false
    phpcs:
      enabled: false
    phpmd:
      enabled: false
    semgrep:
      enabled: false

# =============================================================================
# Chat
# =============================================================================
chat:
  art: false
  auto_reply: true
  integrations:
    jira:
      usage: disabled
    linear:
      usage: disabled

# =============================================================================
# Knowledge Base
# =============================================================================
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
      - "**/RULES.md"
      - "**/.cursorrules"
      - ".github/copilot-instructions.md"
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
  jira:
    usage: disabled
  linear:
    usage: disabled
  mcp:
    usage: auto
    disabled_servers: []

# =============================================================================
# Code Generation
# =============================================================================
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "**/*.go"
        instructions: |
          GoDoc format:
          - First line: FunctionName does X.
          - Describe parameters, return values, errors
          - Mention concurrency safety if relevant
          - Note side effects (file I/O, signals, state changes)
  unit_tests:
    path_instructions:
      - path: "**/*.go"
        instructions: |
          Generate table-driven tests with:
          - Happy path
          - Error cases (invalid input, timeouts, resource unavailable)
          - Edge cases (empty input, max values, concurrent access)
          - For process code: cleanup in t.Cleanup()
          - Use testify/assert, testify/require

# =============================================================================
# Issue Enrichment
# =============================================================================
issue_enrichment:
  auto_enrich:
    enabled: false
  planning:
    enabled: true
    auto_planning:
      enabled: true
      labels:
        - "feature"
        - "enhancement"
        - "bug"
        - "!wip"
  labeling:
    labeling_instructions: []
    auto_apply_labels: false
