---
# Codacy configuration for supervizio/daemon
# Documentation: https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Global path exclusions (analysis + coverage)
exclude_paths:
  # DevContainer and IDE configuration
  - ".devcontainer/**"
  - ".claude/**"
  - ".github/**"
  - ".vscode/**"

  # Documentation and examples
  - "docs/**"
  - "examples/**"
  - "**/*.md"

  # Build artifacts and dependencies
  - "vendor/**"
  - "dist/**"
  - "build/**"

  # Generated code (protobuf, wire, mocks)
  - "**/*.pb.go"
  - "**/*_grpc.pb.go"
  - "**/wire_gen.go"
  - "**/mock_*.go"
  - "src/api/proto/**"

  # Test files and test data
  - "**/*_test.go"
  - "**/testdata/**"

  # Config files
  - "src/.golangci.yml"
  - "src/.ktn-linter.yaml"

engines:
  # Semgrep configuration - no exclusions, issues will be fixed via centralized kernel package
  semgrep:
    enabled: true

  # Markdownlint disabled - using ktn-linter for docs
  markdownlint:
    enabled: false

# Coverage configuration
coverage:
  exclude_paths:
    - "**/*.pb.go"
    - "**/*_grpc.pb.go"
    - "**/wire_gen.go"
    - "src/api/proto/**"
