---
exclude_paths:
  - ".devcontainer/**"
  - ".claude/**"
  - ".github/**"
  - "docs/**"
  - "examples/**"
  - "vendor/**"
  - "dist/**"
  - "build/**"
  - "**/*.md"
  - "**/*_test.go"
  - "**/testdata/**"
  - "src/.golangci.yml"
  - "src/.ktn-linter.yaml"

engines:
  markdownlint:
    enabled: false
  semgrep:
    exclude_paths:
      - "src/internal/infrastructure/process/command.go"
