---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Global exclude patterns - files that should not be analyzed
exclude_paths:
  # DevContainer - development tooling, not production code
  - ".devcontainer/**"

  # Claude configuration
  - ".claude/**"

  # GitHub workflows and config
  - ".github/**"

  # Documentation
  - "docs/**"
  - "**/*.md"

  # Test files
  - "**/*_test.go"
  - "**/testdata/**"

  # Config files (linters, etc.)
  - "src/.golangci.yml"
  - "src/.ktn-linter.yaml"

  # Examples - sample configurations
  - "examples/**"

  # Standard exclusions
  - "vendor/**"
  - "dist/**"
  - "build/**"

# Engines configuration
engines:
  markdownlint:
    enabled: false
