# Codacy Configuration
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

---
exclude_paths:
  # Test files - excluded from analysis
  - "**/*_test.go"
  - "**/*_external_test.go"
  - "**/*_internal_test.go"
