---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Global exclude patterns - files that should not be analyzed
exclude_paths:
  # Test files (Java glob syntax)
  - "**_test.go"
  - "src/**/*_test.go"
  - "**/testdata/**"

  # Documentation files
  - "**.md"
  - "**/*.md"

  # DevContainer prompt files (Markdown used as prompts, not docs)
  - ".devcontainer/docs/**"
  - ".devcontainer/images/.claude/agents/**/*.md"
  - ".devcontainer/images/.claude/commands/**/*.md"

  # YAML config files (duplicate-id false positives)
  - ".devcontainer/images/.claude/agents/review/skills/**"
  - "src/.golangci.yml"

  # Standard exclusions
  - "vendor/**"
  - "dist/**"
  - "build/**"

# Engines configuration
engines:
  markdownlint:
    enabled: false
  semgrep:
    exclude:
      # curl-pipe-bash is intentional for tool installers (sdkman, rustup, pyenv)
      - ".devcontainer/features/languages/*/install.sh"
