---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Global exclude patterns - files that should not be analyzed
exclude_paths:
  # Test files (Java glob syntax)
  - "**_test.go"
  - "src/**/*_test.go"
  - "**/testdata/**"

  # Documentation files
  - "**.md"
  - "**/*.md"

  # Standard exclusions
  - "vendor/**"
  - "dist/**"
  - "build/**"

# Engines configuration
engines:
  markdownlint:
    enabled: false
