---
# Codacy configuration for supervizio/daemon
# Documentation: https://docs.codacy.com/repositories-configure/codacy-configuration-file/

engines:
  # Semgrep configuration
  semgrep:
    exclude_paths:
      # Exclude /proc filesystem readers from file access warnings
      # These files MUST construct dynamic paths to read Linux /proc filesystem
      # The paths are controlled internally (default "/proc") or via constructor for testing
      # No user input reaches these file operations
      - "src/internal/infrastructure/proc/**"

exclude_paths:
  # Test files don't need security analysis
  - "**/*_test.go"
