---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Global exclude patterns - files that should not be analyzed
exclude_paths:
  # Test files
  - '**/*_test.go'
  - '**/testdata/**'

  # Documentation files (internal, not public)
  - '**/*.md'

  # Standard exclusions
  - 'vendor/**'
  - 'dist/**'
  - 'build/**'

# Engines configuration
engines:
  # Disable markdownlint entirely - CLAUDE.md files are internal AI context
  markdownlint:
    enabled: false
