---
# =============================================================================
# Codacy Configuration - supervizio/daemon
# =============================================================================
# PID1-capable process supervisor for containers and Unix systems
# Documentation: https://docs.codacy.com/repositories-configure/codacy-configuration-file/
# =============================================================================

# -----------------------------------------------------------------------------
# Global Exclusions
# -----------------------------------------------------------------------------
exclude_paths:
  # DevContainer and IDE configuration
  - ".devcontainer/**"
  - ".claude/**"
  - ".github/**"
  - ".vscode/**"

  # Documentation and markdown (analyzed separately or excluded)
  - "docs/**"
  - "website/**"
  - "examples/**"
  - "**/*.md"
  - "**/CLAUDE.md"

  # Build artifacts and dependencies
  - "vendor/**"
  - "dist/**"
  - "build/**"
  - "bin/**"
  - "**/target/**"

  # Generated code (protobuf, wire, mocks)
  - "**/*.pb.go"
  - "**/*_grpc.pb.go"
  - "**/wire_gen.go"
  - "**/mock_*.go"
  - "**/*.gen.go"
  - "src/api/proto/**/*.go"

  # E2E test infrastructure (not production code)
  - "e2e/.vagrant/**"
  - "e2e/behavioral/crasher/**"

  # Config files (linter configs, not code)
  - ".golangci.yml"
  - ".ktn-linter.yaml"
  - ".coderabbit.yaml"
  - ".qodo-merge.toml"

# -----------------------------------------------------------------------------
# Languages
# -----------------------------------------------------------------------------
languages:
  go:
    version: "1.25"
  rust:
    version: "1.86"

# -----------------------------------------------------------------------------
# Engines Configuration
# -----------------------------------------------------------------------------
engines:
  # ---------------------------------------------------------------------------
  # Go Static Analysis
  # ---------------------------------------------------------------------------
  # gosec - Security scanner for Go
  gosec:
    enabled: true
    # Exclude G304 (file path from variable) - false positives on procfs readers
    # Security is covered by custom checks
    exclude:
      - "G304"

  # ---------------------------------------------------------------------------
  # Complexity Analysis
  # ---------------------------------------------------------------------------
  # Lizard - Cyclomatic complexity and code length
  lizard:
    enabled: true

  # revive - Go linter (disabled - using golangci-lint + ktn-linter)
  revive:
    enabled: false

  # staticcheck - Advanced Go analysis (via golangci-lint)
  staticcheck:
    enabled: false

  # ---------------------------------------------------------------------------
  # Rust Static Analysis
  # ---------------------------------------------------------------------------
  # clippy - Rust linter
  clippy:
    enabled: true

  # rustfmt - Rust code formatter check
  rustfmt:
    enabled: true

  # ---------------------------------------------------------------------------
  # Security
  # ---------------------------------------------------------------------------
  # Semgrep - Multi-language security scanner
  semgrep:
    enabled: true

  # Trivy - Vulnerability scanner
  trivy:
    enabled: true

  # ---------------------------------------------------------------------------
  # Shell
  # ---------------------------------------------------------------------------
  # ShellCheck - Shell script analysis
  shellcheck:
    enabled: true

  # ---------------------------------------------------------------------------
  # Protobuf
  # ---------------------------------------------------------------------------
  # buf - Protobuf linting (disabled - using buf separately)
  buf:
    enabled: false

  # ---------------------------------------------------------------------------
  # Documentation
  # ---------------------------------------------------------------------------
  # Markdownlint (disabled - ktn-linter handles docs)
  markdownlint:
    enabled: false

  # ---------------------------------------------------------------------------
  # YAML
  # ---------------------------------------------------------------------------
  yamllint:
    enabled: true

  # ---------------------------------------------------------------------------
  # Dockerfile
  # ---------------------------------------------------------------------------
  hadolint:
    enabled: true

# -----------------------------------------------------------------------------
# Coverage Configuration
# -----------------------------------------------------------------------------
coverage:
  # Minimum coverage threshold (%)
  # Note: Platform-specific files (_linux, _darwin, _bsd) may have lower coverage
  # due to CI running on Linux only
  minimum: 60

  # Exclude from coverage calculation
  exclude_paths:
    # Generated code
    - "**/*.pb.go"
    - "**/*_grpc.pb.go"
    - "**/wire_gen.go"
    - "**/mock_*.go"
    - "**/*.gen.go"
    - "src/api/proto/**"

    # Platform-specific code (coverage only on Linux CI)
    - "**/*_darwin.go"
    - "**/*_bsd.go"
    - "**/*_freebsd.go"
    - "**/*_openbsd.go"
    - "**/*_netbsd.go"
    - "**/*_dragonfly.go"

    # Scratch/stub implementations (CI-only)
    - "**/*_scratch.go"

    # E2E tests (separate coverage)
    - "e2e/**"

    # Bootstrap/main (hard to unit test)
    - "src/cmd/**"
    - "src/internal/bootstrap/**"

# -----------------------------------------------------------------------------
# Tool-Specific Settings
# -----------------------------------------------------------------------------
tools:
  gosec:
    patterns:
      # Include all Go files in src/
      include:
        - "src/**/*.go"
      # Exclude generated and test files
      exclude:
        - "**/*_test.go"
        - "**/*.pb.go"
        - "**/wire_gen.go"

  shellcheck:
    patterns:
      include:
        - "**/*.sh"
        - "setup/**"
        - "e2e/**/*.sh"
      exclude:
        - ".devcontainer/**"

  hadolint:
    patterns:
      include:
        - "**/Dockerfile*"
        - "e2e/Dockerfile*"

  clippy:
    patterns:
      include:
        - "src/lib/**/*.rs"
      exclude:
        - "**/target/**"
        - "**/build.rs"

  rustfmt:
    patterns:
      include:
        - "src/lib/**/*.rs"
      exclude:
        - "**/target/**"

  # Lizard - Complexity analysis
  # Exclude test files from complexity checks (table-driven tests are naturally longer)
  lizard:
    patterns:
      include:
        - "src/**/*.go"
        - "src/lib/**/*.rs"
      exclude:
        - "**/*_test.go"
        - "**/*_external_test.go"
        - "**/*_internal_test.go"
        - "**/target/**"
        - "e2e/**"

  # Semgrep - Security scanner
  # Exclude legitimate patterns for system-level code
  semgrep:
    patterns:
      include:
        - "src/**/*.go"
        - "src/lib/**/*.rs"
      exclude:
        # Test files with mock HTTP servers (XSS false positives)
        - "**/*_test.go"
        - "**/*_external_test.go"
        - "**/*_internal_test.go"
        # Probe package uses unsafe for CGO/FFI (legitimate)
        - "src/internal/infrastructure/probe/**"
        # E2E test infrastructure
        - "e2e/**"
