#!/bin/bash
# ============================================================================
# commit-validate.sh - Bloque les commits avec références IA/Claude
# PreToolUse hook pour Bash(git commit:*)
# Exit 0 = autorisé, Exit 2 = bloqué
# ============================================================================

set -uo pipefail

# === Read hook input (JSON from stdin) - fail gracefully ===
set +o pipefail
INPUT="$(cat 2>/dev/null)"
set -o pipefail
INPUT="${INPUT:-{}}"

# Fail gracefully if no input or invalid JSON
if [[ -z "$INPUT" ]] || [[ "$INPUT" == "{}" ]]; then
    exit 0
fi

# Verify jq is available
if ! command -v jq &>/dev/null; then
    exit 0
fi

# Patterns interdits (case insensitive)
FORBIDDEN_PATTERNS=(
    # Co-author patterns
    "co-authored-by.*claude"
    "co-authored-by.*anthropic"
    "co-authored-by.*openai"
    "co-authored-by.*gpt"
    "co-authored-by.*ai"
    "co-authored-by.*copilot"
    "co-authored-by.*gemini"
    "co-authored-by.*llm"
    # Generated by patterns
    "generated.*with.*claude"
    "generated.*by.*claude"
    "generated.*with.*ai"
    "generated.*by.*ai"
    "generated.*with.*gpt"
    "generated.*by.*gpt"
    "ai.assisted"
    "ai-assisted"
    # Direct mentions
    "🤖"
    "claude code"
    "claude-code"
    "anthropic"
    "openai"
    "chatgpt"
    "copilot"
)

# Extraire tool_name et command (fail gracefully)
TOOL=$(printf '%s' "$INPUT" | jq -r '.tool_name // "unknown"' 2>/dev/null) || TOOL="unknown"
COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null) || COMMAND=""

# Vérifier si c'est un git commit
if [[ "$TOOL" != "Bash" ]]; then
    exit 0
fi

if [[ ! "$COMMAND" =~ ^git[[:space:]]+commit ]]; then
    exit 0
fi

# Extraire le message de commit
# Patterns: -m "msg", -m 'msg', --message="msg", heredoc
COMMIT_MSG=""

# Pattern 1: -m "message" ou -m 'message'
if [[ "$COMMAND" =~ -m[[:space:]]+[\"\']([^\"\']+)[\"\'] ]]; then
    COMMIT_MSG="${BASH_REMATCH[1]}"
fi

# Pattern 2: -m "$(cat <<..." (heredoc)
if [[ "$COMMAND" =~ cat[[:space:]]+\<\<[\'\"]?EOF ]]; then
    # Extraire tout entre <<EOF et EOF
    COMMIT_MSG=$(echo "$COMMAND" | sed -n '/<<.*EOF/,/EOF/p' | grep -v "EOF" | grep -v "cat <<")
fi

# Pattern 3: --message="..."
if [[ "$COMMAND" =~ --message=[\"\']([^\"\']+)[\"\'] ]]; then
    COMMIT_MSG="${BASH_REMATCH[1]}"
fi

# Si pas de message trouvé, laisser passer (sera validé autrement)
if [[ -z "$COMMIT_MSG" ]]; then
    exit 0
fi

# Vérifier chaque pattern interdit
COMMIT_MSG_LOWER=$(echo "$COMMIT_MSG" | tr '[:upper:]' '[:lower:]')

for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
    if echo "$COMMIT_MSG_LOWER" | grep -qiE "$pattern"; then
        echo "═══════════════════════════════════════════════"
        echo "  ❌ COMMIT BLOQUÉ - Référence IA détectée"
        echo "═══════════════════════════════════════════════"
        echo ""
        echo "  Pattern interdit trouvé: $pattern"
        echo ""
        echo "  Message de commit:"
        echo "$COMMIT_MSG" | head -5 | sed 's/^/    /'
        echo ""
        echo "  RÈGLE: Les commits ne doivent JAMAIS contenir:"
        echo "    - Co-Authored-By avec Claude/Anthropic/OpenAI/AI"
        echo "    - Generated by/with AI/Claude/GPT"
        echo "    - Mentions directes d'IA (🤖, claude-code, etc.)"
        echo ""
        echo "═══════════════════════════════════════════════"
        exit 2
    fi
done

# Message valide
echo "✓ Commit validé (pas de référence IA)"
exit 0
