// Protocol Buffer definitions for the daemon gRPC API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: daemon.proto

package daemonpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessState represents process lifecycle state.
type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED ProcessState = 0
	ProcessState_PROCESS_STATE_STOPPED     ProcessState = 1
	ProcessState_PROCESS_STATE_STARTING    ProcessState = 2
	ProcessState_PROCESS_STATE_RUNNING     ProcessState = 3
	ProcessState_PROCESS_STATE_STOPPING    ProcessState = 4
	ProcessState_PROCESS_STATE_FAILED      ProcessState = 5
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_STOPPED",
		2: "PROCESS_STATE_STARTING",
		3: "PROCESS_STATE_RUNNING",
		4: "PROCESS_STATE_STOPPING",
		5: "PROCESS_STATE_FAILED",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED": 0,
		"PROCESS_STATE_STOPPED":     1,
		"PROCESS_STATE_STARTING":    2,
		"PROCESS_STATE_RUNNING":     3,
		"PROCESS_STATE_STOPPING":    4,
		"PROCESS_STATE_FAILED":      5,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[0].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[0]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

// StreamStateRequest configures state streaming.
type StreamStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum interval between updates.
	Interval      *durationpb.Duration `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateRequest) Reset() {
	*x = StreamStateRequest{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateRequest) ProtoMessage() {}

func (x *StreamStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateRequest.ProtoReflect.Descriptor instead.
func (*StreamStateRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *StreamStateRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

// StreamMetricsRequest configures metrics streaming.
type StreamMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interval between metric snapshots.
	Interval      *durationpb.Duration `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *StreamMetricsRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

// StreamProcessMetricsRequest configures process metrics streaming.
type StreamProcessMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name to stream metrics for.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Interval between metric snapshots.
	Interval      *durationpb.Duration `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessMetricsRequest) Reset() {
	*x = StreamProcessMetricsRequest{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessMetricsRequest) ProtoMessage() {}

func (x *StreamProcessMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamProcessMetricsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *StreamProcessMetricsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StreamProcessMetricsRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

// GetProcessRequest identifies a process to retrieve.
type GetProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	ServiceName   string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessRequest) Reset() {
	*x = GetProcessRequest{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessRequest) ProtoMessage() {}

func (x *GetProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessRequest.ProtoReflect.Descriptor instead.
func (*GetProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetProcessRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// ListProcessesResponse contains all process metrics.
type ListProcessesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All supervised process metrics.
	Processes     []*ProcessMetrics `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessMetrics {
	if x != nil {
		return x.Processes
	}
	return nil
}

// DaemonState represents the complete daemon state.
type DaemonState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Daemon version.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Daemon start time.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Daemon uptime.
	Uptime *durationpb.Duration `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Overall daemon health.
	Healthy bool `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// All supervised processes.
	Processes []*ProcessMetrics `protobuf:"bytes,5,rep,name=processes,proto3" json:"processes,omitempty"`
	// System metrics snapshot.
	System *SystemMetrics `protobuf:"bytes,6,opt,name=system,proto3" json:"system,omitempty"`
	// Host information.
	Host *HostInfo `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	// Kubernetes information (if running in k8s).
	Kubernetes    *KubernetesInfo `protobuf:"bytes,8,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonState) Reset() {
	*x = DaemonState{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonState) ProtoMessage() {}

func (x *DaemonState) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonState.ProtoReflect.Descriptor instead.
func (*DaemonState) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *DaemonState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DaemonState) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DaemonState) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *DaemonState) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DaemonState) GetProcesses() []*ProcessMetrics {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *DaemonState) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *DaemonState) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *DaemonState) GetKubernetes() *KubernetesInfo {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

// HostInfo contains host system information.
type HostInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Operating system.
	Os string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	// Architecture.
	Arch string `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	// Number of CPUs.
	NumCpus       int32 `protobuf:"varint,4,opt,name=num_cpus,json=numCpus,proto3" json:"num_cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HostInfo) GetNumCpus() int32 {
	if x != nil {
		return x.NumCpus
	}
	return 0
}

// KubernetesInfo contains Kubernetes pod information.
type KubernetesInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pod name.
	PodName string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Namespace.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Node name.
	NodeName string `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Pod labels.
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesInfo) Reset() {
	*x = KubernetesInfo{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesInfo) ProtoMessage() {}

func (x *KubernetesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesInfo.ProtoReflect.Descriptor instead.
func (*KubernetesInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *KubernetesInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *KubernetesInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *KubernetesInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ProcessMetrics contains metrics for a supervised process.
type ProcessMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name from configuration.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Current process ID (0 if not running).
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Current lifecycle state.
	State ProcessState `protobuf:"varint,3,opt,name=state,proto3,enum=daemon.v1.ProcessState" json:"state,omitempty"`
	// Health status.
	Healthy bool `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// CPU metrics.
	Cpu *ProcessCPU `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Memory metrics.
	Memory *ProcessMemory `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	// Process start time.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Process uptime.
	Uptime *durationpb.Duration `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Number of restarts.
	RestartCount int32 `protobuf:"varint,9,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// Last error message (if failed).
	LastError string `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Metrics collection timestamp.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessMetrics) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ProcessMetrics) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetrics) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ProcessMetrics) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProcessMetrics) GetCpu() *ProcessCPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ProcessMetrics) GetMemory() *ProcessMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ProcessMetrics) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProcessMetrics) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *ProcessMetrics) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ProcessMetrics) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ProcessMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ProcessCPU contains CPU metrics for a process.
type ProcessCPU struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User mode CPU time in nanoseconds.
	UserTimeNs uint64 `protobuf:"varint,1,opt,name=user_time_ns,json=userTimeNs,proto3" json:"user_time_ns,omitempty"`
	// System mode CPU time in nanoseconds.
	SystemTimeNs uint64 `protobuf:"varint,2,opt,name=system_time_ns,json=systemTimeNs,proto3" json:"system_time_ns,omitempty"`
	// Total CPU time in nanoseconds.
	TotalTimeNs uint64 `protobuf:"varint,3,opt,name=total_time_ns,json=totalTimeNs,proto3" json:"total_time_ns,omitempty"`
	// CPU usage percentage (0-100 per core).
	UsagePercent  float64 `protobuf:"fixed64,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCPU) Reset() {
	*x = ProcessCPU{}
	mi := &file_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCPU) ProtoMessage() {}

func (x *ProcessCPU) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCPU.ProtoReflect.Descriptor instead.
func (*ProcessCPU) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessCPU) GetUserTimeNs() uint64 {
	if x != nil {
		return x.UserTimeNs
	}
	return 0
}

func (x *ProcessCPU) GetSystemTimeNs() uint64 {
	if x != nil {
		return x.SystemTimeNs
	}
	return 0
}

func (x *ProcessCPU) GetTotalTimeNs() uint64 {
	if x != nil {
		return x.TotalTimeNs
	}
	return 0
}

func (x *ProcessCPU) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

// ProcessMemory contains memory metrics for a process.
type ProcessMemory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resident set size in bytes.
	RssBytes uint64 `protobuf:"varint,1,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	// Virtual memory size in bytes.
	VmsBytes uint64 `protobuf:"varint,2,opt,name=vms_bytes,json=vmsBytes,proto3" json:"vms_bytes,omitempty"`
	// Swap usage in bytes.
	SwapBytes uint64 `protobuf:"varint,3,opt,name=swap_bytes,json=swapBytes,proto3" json:"swap_bytes,omitempty"`
	// Shared memory in bytes.
	SharedBytes uint64 `protobuf:"varint,4,opt,name=shared_bytes,json=sharedBytes,proto3" json:"shared_bytes,omitempty"`
	// Data segment size in bytes.
	DataBytes uint64 `protobuf:"varint,5,opt,name=data_bytes,json=dataBytes,proto3" json:"data_bytes,omitempty"`
	// Stack size in bytes.
	StackBytes    uint64 `protobuf:"varint,6,opt,name=stack_bytes,json=stackBytes,proto3" json:"stack_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMemory) Reset() {
	*x = ProcessMemory{}
	mi := &file_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMemory) ProtoMessage() {}

func (x *ProcessMemory) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMemory.ProtoReflect.Descriptor instead.
func (*ProcessMemory) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessMemory) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessMemory) GetVmsBytes() uint64 {
	if x != nil {
		return x.VmsBytes
	}
	return 0
}

func (x *ProcessMemory) GetSwapBytes() uint64 {
	if x != nil {
		return x.SwapBytes
	}
	return 0
}

func (x *ProcessMemory) GetSharedBytes() uint64 {
	if x != nil {
		return x.SharedBytes
	}
	return 0
}

func (x *ProcessMemory) GetDataBytes() uint64 {
	if x != nil {
		return x.DataBytes
	}
	return 0
}

func (x *ProcessMemory) GetStackBytes() uint64 {
	if x != nil {
		return x.StackBytes
	}
	return 0
}

// SystemMetrics contains system-wide metrics.
type SystemMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System CPU metrics.
	Cpu *SystemCPU `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// System memory metrics.
	Memory *SystemMemory `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	// Load average.
	Load *LoadAverage `protobuf:"bytes,3,opt,name=load,proto3" json:"load,omitempty"`
	// Collection timestamp.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *SystemMetrics) GetCpu() *SystemCPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemMetrics) GetMemory() *SystemMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemMetrics) GetLoad() *LoadAverage {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *SystemMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SystemCPU contains system-wide CPU metrics.
type SystemCPU struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User mode time in nanoseconds.
	UserNs uint64 `protobuf:"varint,1,opt,name=user_ns,json=userNs,proto3" json:"user_ns,omitempty"`
	// Nice time in nanoseconds.
	NiceNs uint64 `protobuf:"varint,2,opt,name=nice_ns,json=niceNs,proto3" json:"nice_ns,omitempty"`
	// System mode time in nanoseconds.
	SystemNs uint64 `protobuf:"varint,3,opt,name=system_ns,json=systemNs,proto3" json:"system_ns,omitempty"`
	// Idle time in nanoseconds.
	IdleNs uint64 `protobuf:"varint,4,opt,name=idle_ns,json=idleNs,proto3" json:"idle_ns,omitempty"`
	// I/O wait time in nanoseconds.
	IowaitNs uint64 `protobuf:"varint,5,opt,name=iowait_ns,json=iowaitNs,proto3" json:"iowait_ns,omitempty"`
	// IRQ time in nanoseconds.
	IrqNs uint64 `protobuf:"varint,6,opt,name=irq_ns,json=irqNs,proto3" json:"irq_ns,omitempty"`
	// Soft IRQ time in nanoseconds.
	SoftirqNs uint64 `protobuf:"varint,7,opt,name=softirq_ns,json=softirqNs,proto3" json:"softirq_ns,omitempty"`
	// Steal time in nanoseconds.
	StealNs uint64 `protobuf:"varint,8,opt,name=steal_ns,json=stealNs,proto3" json:"steal_ns,omitempty"`
	// Overall CPU usage percentage.
	UsagePercent  float64 `protobuf:"fixed64,9,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemCPU) Reset() {
	*x = SystemCPU{}
	mi := &file_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemCPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemCPU) ProtoMessage() {}

func (x *SystemCPU) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemCPU.ProtoReflect.Descriptor instead.
func (*SystemCPU) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *SystemCPU) GetUserNs() uint64 {
	if x != nil {
		return x.UserNs
	}
	return 0
}

func (x *SystemCPU) GetNiceNs() uint64 {
	if x != nil {
		return x.NiceNs
	}
	return 0
}

func (x *SystemCPU) GetSystemNs() uint64 {
	if x != nil {
		return x.SystemNs
	}
	return 0
}

func (x *SystemCPU) GetIdleNs() uint64 {
	if x != nil {
		return x.IdleNs
	}
	return 0
}

func (x *SystemCPU) GetIowaitNs() uint64 {
	if x != nil {
		return x.IowaitNs
	}
	return 0
}

func (x *SystemCPU) GetIrqNs() uint64 {
	if x != nil {
		return x.IrqNs
	}
	return 0
}

func (x *SystemCPU) GetSoftirqNs() uint64 {
	if x != nil {
		return x.SoftirqNs
	}
	return 0
}

func (x *SystemCPU) GetStealNs() uint64 {
	if x != nil {
		return x.StealNs
	}
	return 0
}

func (x *SystemCPU) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

// SystemMemory contains system-wide memory metrics.
type SystemMemory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total memory in bytes.
	TotalBytes uint64 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Available memory in bytes.
	AvailableBytes uint64 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	// Used memory in bytes.
	UsedBytes uint64 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	// Free memory in bytes.
	FreeBytes uint64 `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	// Buffer memory in bytes.
	BuffersBytes uint64 `protobuf:"varint,5,opt,name=buffers_bytes,json=buffersBytes,proto3" json:"buffers_bytes,omitempty"`
	// Cached memory in bytes.
	CachedBytes uint64 `protobuf:"varint,6,opt,name=cached_bytes,json=cachedBytes,proto3" json:"cached_bytes,omitempty"`
	// Shared memory in bytes.
	SharedBytes uint64 `protobuf:"varint,7,opt,name=shared_bytes,json=sharedBytes,proto3" json:"shared_bytes,omitempty"`
	// Total swap in bytes.
	SwapTotalBytes uint64 `protobuf:"varint,8,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"`
	// Used swap in bytes.
	SwapUsedBytes uint64 `protobuf:"varint,9,opt,name=swap_used_bytes,json=swapUsedBytes,proto3" json:"swap_used_bytes,omitempty"`
	// Free swap in bytes.
	SwapFreeBytes uint64 `protobuf:"varint,10,opt,name=swap_free_bytes,json=swapFreeBytes,proto3" json:"swap_free_bytes,omitempty"`
	// Memory usage percentage.
	UsagePercent  float64 `protobuf:"fixed64,11,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMemory) Reset() {
	*x = SystemMemory{}
	mi := &file_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMemory) ProtoMessage() {}

func (x *SystemMemory) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMemory.ProtoReflect.Descriptor instead.
func (*SystemMemory) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *SystemMemory) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *SystemMemory) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *SystemMemory) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *SystemMemory) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *SystemMemory) GetBuffersBytes() uint64 {
	if x != nil {
		return x.BuffersBytes
	}
	return 0
}

func (x *SystemMemory) GetCachedBytes() uint64 {
	if x != nil {
		return x.CachedBytes
	}
	return 0
}

func (x *SystemMemory) GetSharedBytes() uint64 {
	if x != nil {
		return x.SharedBytes
	}
	return 0
}

func (x *SystemMemory) GetSwapTotalBytes() uint64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

func (x *SystemMemory) GetSwapUsedBytes() uint64 {
	if x != nil {
		return x.SwapUsedBytes
	}
	return 0
}

func (x *SystemMemory) GetSwapFreeBytes() uint64 {
	if x != nil {
		return x.SwapFreeBytes
	}
	return 0
}

func (x *SystemMemory) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

// LoadAverage contains system load averages.
type LoadAverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-minute load average.
	Load1 float64 `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"`
	// 5-minute load average.
	Load5 float64 `protobuf:"fixed64,2,opt,name=load5,proto3" json:"load5,omitempty"`
	// 15-minute load average.
	Load15        float64 `protobuf:"fixed64,3,opt,name=load15,proto3" json:"load15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	mi := &file_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *LoadAverage) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *LoadAverage) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *LoadAverage) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\tdaemon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"K\n" +
	"\x12StreamStateRequest\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\"M\n" +
	"\x14StreamMetricsRequest\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\"w\n" +
	"\x1bStreamProcessMetricsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x125\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\binterval\"6\n" +
	"\x11GetProcessRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"P\n" +
	"\x15ListProcessesResponse\x127\n" +
	"\tprocesses\x18\x01 \x03(\v2\x19.daemon.v1.ProcessMetricsR\tprocesses\"\xfe\x02\n" +
	"\vDaemonState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x121\n" +
	"\x06uptime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x127\n" +
	"\tprocesses\x18\x05 \x03(\v2\x19.daemon.v1.ProcessMetricsR\tprocesses\x120\n" +
	"\x06system\x18\x06 \x01(\v2\x18.daemon.v1.SystemMetricsR\x06system\x12'\n" +
	"\x04host\x18\a \x01(\v2\x13.daemon.v1.HostInfoR\x04host\x129\n" +
	"\n" +
	"kubernetes\x18\b \x01(\v2\x19.daemon.v1.KubernetesInfoR\n" +
	"kubernetes\"e\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x19\n" +
	"\bnum_cpus\x18\x04 \x01(\x05R\anumCpus\"\xe0\x01\n" +
	"\x0eKubernetesInfo\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12=\n" +
	"\x06labels\x18\x04 \x03(\v2%.daemon.v1.KubernetesInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x03\n" +
	"\x0eProcessMetrics\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.daemon.v1.ProcessStateR\x05state\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12'\n" +
	"\x03cpu\x18\x05 \x01(\v2\x15.daemon.v1.ProcessCPUR\x03cpu\x120\n" +
	"\x06memory\x18\x06 \x01(\v2\x18.daemon.v1.ProcessMemoryR\x06memory\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x121\n" +
	"\x06uptime\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12#\n" +
	"\rrestart_count\x18\t \x01(\x05R\frestartCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9d\x01\n" +
	"\n" +
	"ProcessCPU\x12 \n" +
	"\fuser_time_ns\x18\x01 \x01(\x04R\n" +
	"userTimeNs\x12$\n" +
	"\x0esystem_time_ns\x18\x02 \x01(\x04R\fsystemTimeNs\x12\"\n" +
	"\rtotal_time_ns\x18\x03 \x01(\x04R\vtotalTimeNs\x12#\n" +
	"\rusage_percent\x18\x04 \x01(\x01R\fusagePercent\"\xcb\x01\n" +
	"\rProcessMemory\x12\x1b\n" +
	"\trss_bytes\x18\x01 \x01(\x04R\brssBytes\x12\x1b\n" +
	"\tvms_bytes\x18\x02 \x01(\x04R\bvmsBytes\x12\x1d\n" +
	"\n" +
	"swap_bytes\x18\x03 \x01(\x04R\tswapBytes\x12!\n" +
	"\fshared_bytes\x18\x04 \x01(\x04R\vsharedBytes\x12\x1d\n" +
	"\n" +
	"data_bytes\x18\x05 \x01(\x04R\tdataBytes\x12\x1f\n" +
	"\vstack_bytes\x18\x06 \x01(\x04R\n" +
	"stackBytes\"\xce\x01\n" +
	"\rSystemMetrics\x12&\n" +
	"\x03cpu\x18\x01 \x01(\v2\x14.daemon.v1.SystemCPUR\x03cpu\x12/\n" +
	"\x06memory\x18\x02 \x01(\v2\x17.daemon.v1.SystemMemoryR\x06memory\x12*\n" +
	"\x04load\x18\x03 \x01(\v2\x16.daemon.v1.LoadAverageR\x04load\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x86\x02\n" +
	"\tSystemCPU\x12\x17\n" +
	"\auser_ns\x18\x01 \x01(\x04R\x06userNs\x12\x17\n" +
	"\anice_ns\x18\x02 \x01(\x04R\x06niceNs\x12\x1b\n" +
	"\tsystem_ns\x18\x03 \x01(\x04R\bsystemNs\x12\x17\n" +
	"\aidle_ns\x18\x04 \x01(\x04R\x06idleNs\x12\x1b\n" +
	"\tiowait_ns\x18\x05 \x01(\x04R\biowaitNs\x12\x15\n" +
	"\x06irq_ns\x18\x06 \x01(\x04R\x05irqNs\x12\x1d\n" +
	"\n" +
	"softirq_ns\x18\a \x01(\x04R\tsoftirqNs\x12\x19\n" +
	"\bsteal_ns\x18\b \x01(\x04R\astealNs\x12#\n" +
	"\rusage_percent\x18\t \x01(\x01R\fusagePercent\"\xa0\x03\n" +
	"\fSystemMemory\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x04R\tfreeBytes\x12#\n" +
	"\rbuffers_bytes\x18\x05 \x01(\x04R\fbuffersBytes\x12!\n" +
	"\fcached_bytes\x18\x06 \x01(\x04R\vcachedBytes\x12!\n" +
	"\fshared_bytes\x18\a \x01(\x04R\vsharedBytes\x12(\n" +
	"\x10swap_total_bytes\x18\b \x01(\x04R\x0eswapTotalBytes\x12&\n" +
	"\x0fswap_used_bytes\x18\t \x01(\x04R\rswapUsedBytes\x12&\n" +
	"\x0fswap_free_bytes\x18\n" +
	" \x01(\x04R\rswapFreeBytes\x12#\n" +
	"\rusage_percent\x18\v \x01(\x01R\fusagePercent\"Q\n" +
	"\vLoadAverage\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x02 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x03 \x01(\x01R\x06load15*\xb5\x01\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROCESS_STATE_STOPPED\x10\x01\x12\x1a\n" +
	"\x16PROCESS_STATE_STARTING\x10\x02\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x03\x12\x1a\n" +
	"\x16PROCESS_STATE_STOPPING\x10\x04\x12\x18\n" +
	"\x14PROCESS_STATE_FAILED\x10\x052\x82\x03\n" +
	"\rDaemonService\x12:\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x16.daemon.v1.DaemonState\x12F\n" +
	"\vStreamState\x12\x1d.daemon.v1.StreamStateRequest\x1a\x16.daemon.v1.DaemonState0\x01\x12I\n" +
	"\rListProcesses\x12\x16.google.protobuf.Empty\x1a .daemon.v1.ListProcessesResponse\x12E\n" +
	"\n" +
	"GetProcess\x12\x1c.daemon.v1.GetProcessRequest\x1a\x19.daemon.v1.ProcessMetrics\x12[\n" +
	"\x14StreamProcessMetrics\x12&.daemon.v1.StreamProcessMetricsRequest\x1a\x19.daemon.v1.ProcessMetrics0\x012\xe0\x02\n" +
	"\x0eMetricsService\x12D\n" +
	"\x10GetSystemMetrics\x12\x16.google.protobuf.Empty\x1a\x18.daemon.v1.SystemMetrics\x12R\n" +
	"\x13StreamSystemMetrics\x12\x1f.daemon.v1.StreamMetricsRequest\x1a\x18.daemon.v1.SystemMetrics0\x01\x12[\n" +
	"\x14StreamProcessMetrics\x12&.daemon.v1.StreamProcessMetricsRequest\x1a\x19.daemon.v1.ProcessMetrics0\x01\x12W\n" +
	"\x17StreamAllProcessMetrics\x12\x1f.daemon.v1.StreamMetricsRequest\x1a\x19.daemon.v1.ProcessMetrics0\x01B8Z6github.com/kodflow/daemon/api/proto/v1/daemon;daemonpbb\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_daemon_proto_goTypes = []any{
	(ProcessState)(0),                   // 0: daemon.v1.ProcessState
	(*StreamStateRequest)(nil),          // 1: daemon.v1.StreamStateRequest
	(*StreamMetricsRequest)(nil),        // 2: daemon.v1.StreamMetricsRequest
	(*StreamProcessMetricsRequest)(nil), // 3: daemon.v1.StreamProcessMetricsRequest
	(*GetProcessRequest)(nil),           // 4: daemon.v1.GetProcessRequest
	(*ListProcessesResponse)(nil),       // 5: daemon.v1.ListProcessesResponse
	(*DaemonState)(nil),                 // 6: daemon.v1.DaemonState
	(*HostInfo)(nil),                    // 7: daemon.v1.HostInfo
	(*KubernetesInfo)(nil),              // 8: daemon.v1.KubernetesInfo
	(*ProcessMetrics)(nil),              // 9: daemon.v1.ProcessMetrics
	(*ProcessCPU)(nil),                  // 10: daemon.v1.ProcessCPU
	(*ProcessMemory)(nil),               // 11: daemon.v1.ProcessMemory
	(*SystemMetrics)(nil),               // 12: daemon.v1.SystemMetrics
	(*SystemCPU)(nil),                   // 13: daemon.v1.SystemCPU
	(*SystemMemory)(nil),                // 14: daemon.v1.SystemMemory
	(*LoadAverage)(nil),                 // 15: daemon.v1.LoadAverage
	nil,                                 // 16: daemon.v1.KubernetesInfo.LabelsEntry
	(*durationpb.Duration)(nil),         // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),       // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 19: google.protobuf.Empty
}
var file_daemon_proto_depIdxs = []int32{
	17, // 0: daemon.v1.StreamStateRequest.interval:type_name -> google.protobuf.Duration
	17, // 1: daemon.v1.StreamMetricsRequest.interval:type_name -> google.protobuf.Duration
	17, // 2: daemon.v1.StreamProcessMetricsRequest.interval:type_name -> google.protobuf.Duration
	9,  // 3: daemon.v1.ListProcessesResponse.processes:type_name -> daemon.v1.ProcessMetrics
	18, // 4: daemon.v1.DaemonState.start_time:type_name -> google.protobuf.Timestamp
	17, // 5: daemon.v1.DaemonState.uptime:type_name -> google.protobuf.Duration
	9,  // 6: daemon.v1.DaemonState.processes:type_name -> daemon.v1.ProcessMetrics
	12, // 7: daemon.v1.DaemonState.system:type_name -> daemon.v1.SystemMetrics
	7,  // 8: daemon.v1.DaemonState.host:type_name -> daemon.v1.HostInfo
	8,  // 9: daemon.v1.DaemonState.kubernetes:type_name -> daemon.v1.KubernetesInfo
	16, // 10: daemon.v1.KubernetesInfo.labels:type_name -> daemon.v1.KubernetesInfo.LabelsEntry
	0,  // 11: daemon.v1.ProcessMetrics.state:type_name -> daemon.v1.ProcessState
	10, // 12: daemon.v1.ProcessMetrics.cpu:type_name -> daemon.v1.ProcessCPU
	11, // 13: daemon.v1.ProcessMetrics.memory:type_name -> daemon.v1.ProcessMemory
	18, // 14: daemon.v1.ProcessMetrics.start_time:type_name -> google.protobuf.Timestamp
	17, // 15: daemon.v1.ProcessMetrics.uptime:type_name -> google.protobuf.Duration
	18, // 16: daemon.v1.ProcessMetrics.timestamp:type_name -> google.protobuf.Timestamp
	13, // 17: daemon.v1.SystemMetrics.cpu:type_name -> daemon.v1.SystemCPU
	14, // 18: daemon.v1.SystemMetrics.memory:type_name -> daemon.v1.SystemMemory
	15, // 19: daemon.v1.SystemMetrics.load:type_name -> daemon.v1.LoadAverage
	18, // 20: daemon.v1.SystemMetrics.timestamp:type_name -> google.protobuf.Timestamp
	19, // 21: daemon.v1.DaemonService.GetState:input_type -> google.protobuf.Empty
	1,  // 22: daemon.v1.DaemonService.StreamState:input_type -> daemon.v1.StreamStateRequest
	19, // 23: daemon.v1.DaemonService.ListProcesses:input_type -> google.protobuf.Empty
	4,  // 24: daemon.v1.DaemonService.GetProcess:input_type -> daemon.v1.GetProcessRequest
	3,  // 25: daemon.v1.DaemonService.StreamProcessMetrics:input_type -> daemon.v1.StreamProcessMetricsRequest
	19, // 26: daemon.v1.MetricsService.GetSystemMetrics:input_type -> google.protobuf.Empty
	2,  // 27: daemon.v1.MetricsService.StreamSystemMetrics:input_type -> daemon.v1.StreamMetricsRequest
	3,  // 28: daemon.v1.MetricsService.StreamProcessMetrics:input_type -> daemon.v1.StreamProcessMetricsRequest
	2,  // 29: daemon.v1.MetricsService.StreamAllProcessMetrics:input_type -> daemon.v1.StreamMetricsRequest
	6,  // 30: daemon.v1.DaemonService.GetState:output_type -> daemon.v1.DaemonState
	6,  // 31: daemon.v1.DaemonService.StreamState:output_type -> daemon.v1.DaemonState
	5,  // 32: daemon.v1.DaemonService.ListProcesses:output_type -> daemon.v1.ListProcessesResponse
	9,  // 33: daemon.v1.DaemonService.GetProcess:output_type -> daemon.v1.ProcessMetrics
	9,  // 34: daemon.v1.DaemonService.StreamProcessMetrics:output_type -> daemon.v1.ProcessMetrics
	12, // 35: daemon.v1.MetricsService.GetSystemMetrics:output_type -> daemon.v1.SystemMetrics
	12, // 36: daemon.v1.MetricsService.StreamSystemMetrics:output_type -> daemon.v1.SystemMetrics
	9,  // 37: daemon.v1.MetricsService.StreamProcessMetrics:output_type -> daemon.v1.ProcessMetrics
	9,  // 38: daemon.v1.MetricsService.StreamAllProcessMetrics:output_type -> daemon.v1.ProcessMetrics
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
