// Protocol Buffer definitions for the daemon gRPC API.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: daemon.proto

package daemonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_GetState_FullMethodName             = "/daemon.v1.DaemonService/GetState"
	DaemonService_StreamState_FullMethodName          = "/daemon.v1.DaemonService/StreamState"
	DaemonService_ListProcesses_FullMethodName        = "/daemon.v1.DaemonService/ListProcesses"
	DaemonService_GetProcess_FullMethodName           = "/daemon.v1.DaemonService/GetProcess"
	DaemonService_StreamProcessMetrics_FullMethodName = "/daemon.v1.DaemonService/StreamProcessMetrics"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService provides daemon state and process management.
type DaemonServiceClient interface {
	// GetState returns the current daemon state.
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonState, error)
	// StreamState streams daemon state updates.
	StreamState(ctx context.Context, in *StreamStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DaemonState], error)
	// ListProcesses returns all supervised processes.
	ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	// GetProcess returns a specific process by name.
	GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*ProcessMetrics, error)
	// StreamProcessMetrics streams metrics for a specific process.
	StreamProcessMetrics(ctx context.Context, in *StreamProcessMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessMetrics], error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonState)
	err := c.cc.Invoke(ctx, DaemonService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StreamState(ctx context.Context, in *StreamStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DaemonState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_StreamState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStateRequest, DaemonState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamStateClient = grpc.ServerStreamingClient[DaemonState]

func (c *daemonServiceClient) ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*ProcessMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessMetrics)
	err := c.cc.Invoke(ctx, DaemonService_GetProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StreamProcessMetrics(ctx context.Context, in *StreamProcessMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[1], DaemonService_StreamProcessMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProcessMetricsRequest, ProcessMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamProcessMetricsClient = grpc.ServerStreamingClient[ProcessMetrics]

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService provides daemon state and process management.
type DaemonServiceServer interface {
	// GetState returns the current daemon state.
	GetState(context.Context, *emptypb.Empty) (*DaemonState, error)
	// StreamState streams daemon state updates.
	StreamState(*StreamStateRequest, grpc.ServerStreamingServer[DaemonState]) error
	// ListProcesses returns all supervised processes.
	ListProcesses(context.Context, *emptypb.Empty) (*ListProcessesResponse, error)
	// GetProcess returns a specific process by name.
	GetProcess(context.Context, *GetProcessRequest) (*ProcessMetrics, error)
	// StreamProcessMetrics streams metrics for a specific process.
	StreamProcessMetrics(*StreamProcessMetricsRequest, grpc.ServerStreamingServer[ProcessMetrics]) error
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) GetState(context.Context, *emptypb.Empty) (*DaemonState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedDaemonServiceServer) StreamState(*StreamStateRequest, grpc.ServerStreamingServer[DaemonState]) error {
	return status.Error(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedDaemonServiceServer) ListProcesses(context.Context, *emptypb.Empty) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedDaemonServiceServer) GetProcess(context.Context, *GetProcessRequest) (*ProcessMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcess not implemented")
}
func (UnimplementedDaemonServiceServer) StreamProcessMetrics(*StreamProcessMetricsRequest, grpc.ServerStreamingServer[ProcessMetrics]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessMetrics not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).StreamState(m, &grpc.GenericServerStream[StreamStateRequest, DaemonState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamStateServer = grpc.ServerStreamingServer[DaemonState]

func _DaemonService_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListProcesses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetProcess(ctx, req.(*GetProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StreamProcessMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProcessMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).StreamProcessMetrics(m, &grpc.GenericServerStream[StreamProcessMetricsRequest, ProcessMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamProcessMetricsServer = grpc.ServerStreamingServer[ProcessMetrics]

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _DaemonService_GetState_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _DaemonService_ListProcesses_Handler,
		},
		{
			MethodName: "GetProcess",
			Handler:    _DaemonService_GetProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _DaemonService_StreamState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamProcessMetrics",
			Handler:       _DaemonService_StreamProcessMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}

const (
	MetricsService_GetSystemMetrics_FullMethodName        = "/daemon.v1.MetricsService/GetSystemMetrics"
	MetricsService_StreamSystemMetrics_FullMethodName     = "/daemon.v1.MetricsService/StreamSystemMetrics"
	MetricsService_StreamProcessMetrics_FullMethodName    = "/daemon.v1.MetricsService/StreamProcessMetrics"
	MetricsService_StreamAllProcessMetrics_FullMethodName = "/daemon.v1.MetricsService/StreamAllProcessMetrics"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetricsService provides system and process metrics streaming.
type MetricsServiceClient interface {
	// GetSystemMetrics returns current system metrics.
	GetSystemMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemMetrics, error)
	// StreamSystemMetrics streams system metrics at specified interval.
	StreamSystemMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemMetrics], error)
	// StreamProcessMetrics streams process metrics at specified interval.
	StreamProcessMetrics(ctx context.Context, in *StreamProcessMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessMetrics], error)
	// StreamAllProcessMetrics streams metrics for all processes.
	StreamAllProcessMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessMetrics], error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) GetSystemMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemMetrics)
	err := c.cc.Invoke(ctx, MetricsService_GetSystemMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) StreamSystemMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[0], MetricsService_StreamSystemMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, SystemMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamSystemMetricsClient = grpc.ServerStreamingClient[SystemMetrics]

func (c *metricsServiceClient) StreamProcessMetrics(ctx context.Context, in *StreamProcessMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[1], MetricsService_StreamProcessMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProcessMetricsRequest, ProcessMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamProcessMetricsClient = grpc.ServerStreamingClient[ProcessMetrics]

func (c *metricsServiceClient) StreamAllProcessMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[2], MetricsService_StreamAllProcessMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, ProcessMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamAllProcessMetricsClient = grpc.ServerStreamingClient[ProcessMetrics]

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
//
// MetricsService provides system and process metrics streaming.
type MetricsServiceServer interface {
	// GetSystemMetrics returns current system metrics.
	GetSystemMetrics(context.Context, *emptypb.Empty) (*SystemMetrics, error)
	// StreamSystemMetrics streams system metrics at specified interval.
	StreamSystemMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[SystemMetrics]) error
	// StreamProcessMetrics streams process metrics at specified interval.
	StreamProcessMetrics(*StreamProcessMetricsRequest, grpc.ServerStreamingServer[ProcessMetrics]) error
	// StreamAllProcessMetrics streams metrics for all processes.
	StreamAllProcessMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[ProcessMetrics]) error
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) GetSystemMetrics(context.Context, *emptypb.Empty) (*SystemMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) StreamSystemMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[SystemMetrics]) error {
	return status.Error(codes.Unimplemented, "method StreamSystemMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) StreamProcessMetrics(*StreamProcessMetricsRequest, grpc.ServerStreamingServer[ProcessMetrics]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) StreamAllProcessMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[ProcessMetrics]) error {
	return status.Error(codes.Unimplemented, "method StreamAllProcessMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_GetSystemMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetSystemMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetSystemMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetSystemMetrics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_StreamSystemMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).StreamSystemMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, SystemMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamSystemMetricsServer = grpc.ServerStreamingServer[SystemMetrics]

func _MetricsService_StreamProcessMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProcessMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).StreamProcessMetrics(m, &grpc.GenericServerStream[StreamProcessMetricsRequest, ProcessMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamProcessMetricsServer = grpc.ServerStreamingServer[ProcessMetrics]

func _MetricsService_StreamAllProcessMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).StreamAllProcessMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, ProcessMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamAllProcessMetricsServer = grpc.ServerStreamingServer[ProcessMetrics]

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.v1.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemMetrics",
			Handler:    _MetricsService_GetSystemMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSystemMetrics",
			Handler:       _MetricsService_StreamSystemMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamProcessMetrics",
			Handler:       _MetricsService_StreamProcessMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAllProcessMetrics",
			Handler:       _MetricsService_StreamAllProcessMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
