version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  exclusions:
    rules:
      # Test files
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst

      # Platform-specific files
      - path: (_linux|_darwin|_bsd|_unix)\.go
        linters:
          - dupl

      # G304 (file inclusion via variable) is expected in /proc readers
      - path: /proc/
        text: "G304"
        linters:
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kodflow/daemon

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 256

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  exhaustive:
    default-signifies-exhaustive: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
        disabled: true
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
