version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  # ktn-linter handles test file style rules
  tests: false

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    # gosec disabled - G304 false positives on /proc readers, Codacy handles security
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    # revive disabled - ktn-linter is the source of truth for code style
    # revive's var-declaration conflicts with KTN-VAR-EXPLICIT
    # revive's unused-parameter conflicts with KTN-FUNC-BLANKPARAM
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 256

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  exhaustive:
    default-signifies-exhaustive: true

  goimports:
    local-prefixes: github.com/kodflow/daemon

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-generated: strict
  exclude-dirs:
    - api/proto
  exclude-rules:
    # Generated files (Wire, protobuf, etc.)
    - path: wire_gen\.go
      linters:
        - all
    - path: \.pb\.go$
      linters:
        - all
    - path: _grpc\.pb\.go$
      linters:
        - all

    # Platform-specific files
    - path: (_linux|_darwin|_bsd|_unix)\.go
      linters:
        - dupl
